name: CI/CD

on:
  push:
 
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Publish to NPM
        if: matrix.package == '@credix/credix-client' && contains(fromJSON('["mainnet", "pre-mainnet"]'), github.ref_name)
        run: npm publish --access public --tag beta
        #TODO: Remove this line once we published successfully
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
